@startuml
control "Named Event Loop" as el

box "named state Foo" #LightBlue
participant "My Function: add 1" as my1
participant "My Function: add 2" as my2
end box

box "named state Bar" #LightGreen
participant "My Function: add 1" as my4
participant "My Function: add 3" as my3
end box

el  -> my1 : input 0
my1 -> my1 : add 1
el  <- my1 : return 1


el ->  my2 : input 1
my2 -> my2 : add 2
el  <- my2 : return 3


el -> my1  : input 3
my1 -> my1 : add 1
el  <- my1 : return 4


el ->  my3 : input 0
my3 -> my3 : add 3
el  <- my3 : return 3

el ->  my4 : input 3
my4 -> my4 : add 1
el  <- my4 : return 4
@enduml


